# Generated by Django 5.1.7 on 2025-03-26 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0002_alter_invoice_truck_number_alter_invoicedetail_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="invoice",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="invoices.invoice",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="InvoiceDetail",
        ),
    ]
