# Generated by Django 5.1.1 on 2025-03-26 12:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0003_item_invoice_delete_invoicedetail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="weight",
            new_name="quantity",
        ),
    ]
